export const RECEIVE_MESSAGE = 'home/RECEIVE_MESSAGE';
export const RECEIVE_PRIVATE_MESSAGE = 'home/RECEIVE_PRIVATE_MESSAGE';
export const PUSH_MESSAGE = 'home/PUSH_MESSAGE';
export const UPDATE_ONLINE_USERS = 'home/UPDATE_ONLINE_USERS';
export const CHANGE_ROOM_TITLE = 'home/CHANGE_ROOM_TITLE';
export const TOGGLE_SHOW_SEARCH_USERS = 'home/TOGGLE_SHOW_SEARCH_USERS';
export const CHANGE_SEARCH_USERS = 'home/CHANGE_SEARCH_USERS';
